accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    # path('registration/', views.RegistrationView.as_view(template_name='accounts/registration.html'),
    #      name='registration'),
    path('settings', views.SettingsView.as_view(), name='settings'),
]

main/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from welcome.views import index, health

urlpatterns = [

    path('', index),
    path('health', health),
    path('admin/', admin.site.urls),
]
#
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class PokerUser(AbstractUser):
    nick_name = models.CharField(max_length=64, blank=True, null=True)
    REQUIRED_FIELDS = ['email']

welcome/models.py
from django.db import models

# Create your models here.

class PageView(models.Model):
    hostname = models.CharField(max_length=32)
    timestamp = models.DateTimeField(auto_now_add=True)

class Beer(models.Model):
    typo = models.CharField(max_length=256)

accounts/forms.py
from django import forms

from accounts.models import PokerUser


class PersonalDetailsForm(forms.ModelForm):
    class Meta:
        model = PokerUser
        exclude = ('team', 'user',)

        # widgets = {
        #     'chart_type': forms.Select(choices=CHART_CHOICES),
        # }

accounts/views.py
from django.views.generic import TemplateView


class SettingsView(TemplateView):
    template_name = 'accounts/account_settings.html'

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            print('User known')
        else:
            print('Anonymous')

welcome/views.py
import os
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse

from . import database
from .models import PageView


def index(request):
    hostname = os.getenv('HOSTNAME', 'unknown')
    PageView.objects.create(hostname=hostname)

    db_name = os.getenv('DATABASE_NAME')
    db_user = os.getenv('DATABASE_USER')
    engine = os.getenv('DATABASE_ENGINE')
    host = os.getenv('DATABASE_HOST')

    print('db name, user, engine, host')
    print(db_name)
    print(db_user)
    print(engine)
    print(host)

    return render(request, 'welcome/index.html', {
        'hostname': hostname,
        'database': database.info(),
        'count': PageView.objects.count(),
    })


def health(request):
    return HttpResponse(PageView.objects.count())

accounts/templates/accounts/account_settings.html
<h1>Settings</h1>

main/templates/alerts.html
{% if alert %}
    <div class="row">
        <div class="alert alert-{{ alert_level }}" role="alert">{{ text }}</div>
    </div>
{% endif %}

main/templates/layout.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Chart javascript -->
    <script src="{{ STATIC_URL }}highcharts/highcharts.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/index.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap4/css/bootstrap.min.css">
    {#    <script src="https://code.highcharts.com/highcharts.js"></script>#}
    {#    <script src="https://code.highcharts.com/modules/exporting.js"></script>#}
     <!-- Bootstrap Javascript -->
    <script src="{{ STATIC_URL }}jquery/jquery-3.2.1.min.js"></script>
    <script src="{{ STATIC_URL }}popper/popper.js"></script>
    <script src="{{ STATIC_URL }}bootstrap4/js/bootstrap.min.js"></script>

    <title>KPN Digital</title>
</head>
<body>
{% include 'navbar.html' %}
{% include 'alerts.html' %}
<div class="background-image">
    {% if dev %}
        <div class="alert alert-warning text-center" role="alert">
            You're currently working on the local dev environment!
        </div>


    {% endif %}
    <div class="container">
        {% block content %}


        {% endblock %}
    </div>
</div>


</body>
</html>

main/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">KPN Digital</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" {##}id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {#            <li class="nav-item">#}
            {#                <a class="nav-link {{ retro_nav }}" href="{% url 'tosti:index' %}">Tosti</a>#}
            {#            </li>#}
            {# Menu items available only for logged in users #}
            {% if user.is_authenticated %}
                {#            <li class="nav-item">#}
                {#                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>#}
                {#            </li>#}
                <li class="nav-item">
{#                    <a class="nav-link {{ retro_nav }}" href="{% url 'retrospective:index' %}">Retrospectives</a>#}
                </li>
                {#            <li class="nav-item">#}
                {#                <a class="nav-link {{ actions_nav }}" href="{% url 'retrospective:actions' %}">Actions</a>#}
                {#            </li>#}

                <ul class="navbar-nav actions">
                    {#                    <li class="nav-item login-item">#}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {{ actions_nav }}" data-toggle="dropdown" href="#"
                           role="button"
                           aria-haspopup="true" aria-expanded="false" id="actionDropDown">Actions</a>
                        <div class="dropdown-menu" aria-labelledby="actionDropDown">
{#                            <a class="dropdown-item" href="{% url 'retrospective:action-status' 'open' %}">Overview</a>#}
{#                            <a class="dropdown-item" href="{% url 'retrospective:add-action' %}">Add action</a>#}
{#                            <a class="dropdown-item" href="{% url 'retrospective:feedback' %}">Add feedback</a>#}
                        </div>

                    </li>
                </ul>

                </ul>


                <ul class="navbar-nav mr-right login">
                <li class="nav-item login-item">

                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">{{ user }}</a>
                <div class="dropdown-menu">
{#                    <a class="dropdown-item {{ login_nav }}" href="{% url 'accounts:settings' %}">Settings</a>#}
{#                    <a class="dropdown-item {{ login_nav }}" href="{% url 'accounts:logout' %}">Logout</a>#}
                </div>
            {% else %}
{#                <a class="nav-link {{ login_nav }}" href="{% url 'accounts:login' %}">Login</a>#}
            {% endif %}

            </li>
            </ul>


    </div>
</nav>
{##}
{##}
{#<nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#    <div class="container-fluid">#}
{#        <!-- Brand and toggle get grouped for better mobile display -->#}
{#        <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"#}
{#                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">#}
{#                <span class="sr-only">Toggle navigation</span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
{#            <a class="navbar-brand" href="/">KPN Digital</a>#}
{#        </div>#}
{##}
{#        <!-- Collect the nav links, forms, and other content for toggling -->#}
{#        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#            <ul class="nav navbar-nav">#}
{#                <li class={{ tosti }}><a href="{% url 'tosti:index' %}">Tosti <span class="sr-only">(current)</span></a>#}
{#                </li>#}
{#                <li class=""><a href="">Retrospectives</a></li>#}
{#                <li class=""><a href="{% url 'feedback:index' %}">MijnKPN</a></li>#}
{#                <li class=""><a href="">Quiz</a></li>#}
{##}
{#                <li><a class="modal" data-toggle="modal" data-target="#about">Ideas?</a></li>#}
{#            </ul>#}
{##}
{##}
{#            <!-- Modal button -->#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a class="modal" data-toggle="modal" data-target="#about">About</a></li>#}
{#            </ul>#}
{##}
{#            {% include 'modal.html' %}#}
{##}
{#            {% if user.is_authenticated %}#}
{#                <ul class="nav navbar-nav navbar-right">#}
{#                    <li class="dropdown active {{ login }}">#}
{#                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                           aria-expanded="false">{{ user|title }} <span class="caret"></span></a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a href="{% url 'accounts:settings' %}">Settings</a></li>#}
{#                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>#}
{#                            <li><a href="#">Something else here</a></li>#}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li><a href="#">Separated link</a></li>#}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li><a href="#">One more separated link</a></li>#}
{#                        </ul>#}
{#                    </li>#}
{#                </ul>#}
{##}
{#            {% else %}#}
{##}
{#                <ul class="nav navbar-nav navbar-right">#}
{#                    <li class={{ login }}><a href="{% url 'accounts:login' %}">Login</a></li>#}
{#                </ul>#}
{##}
{##}
{##}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
</nav>

welcome/templates/welcome/index.html
{% extends 'layout.html' %}


{% block content %}
    <h1>Welcome to a django app on openshift</h1>

{% endblock %}